version: '3'
services:
  mysqlsrv:
    build:
      context: ./dbase
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "mysqlsrv"
    ports:
      - "3306:3306"
    volumes:
      - ./dbase/scripts:/docker-entrypoint-initdb.d
      - ./dbase/data:/var/lib/mysql
    networks:
      - proj-network
  adminer:
    image: adminer
    depends_on:
      - mysqlsrv
    ports:
      - 8081:8080
    networks:
      - proj-network
  web:
    build: .
    depends_on:
      - mysqlsrv
    ports:
      - 5000:5000
    networks:
      - proj-network
networks:
  proj-network:
    driver: bridge
